version: "0.7.0"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: caravan_server_1
      APP_PORT: 2272
  server:
    image: caravan:latest
    user: "1000:1000"
    init: true
