version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: caravan-app_server_1
      APP_PORT: 2272
  server:
    image: jbrauck/caravan-umbrel:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "4137:4137"
    user: "1000:1000"
